-- begin PRACTICE_SESSION
alter table PRACTICE_SESSION add constraint FK_PRACTICE_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references PRACTICE_SPEAKER(ID)^
create index IDX_PRACTICE_SESSION_ON_SPEAKER on PRACTICE_SESSION (SPEAKER_ID)^
-- end PRACTICE_SESSION
-- begin PRACTICE_SPEAKER
create unique index IDX_PRACTICE_SPEAKER_UNIQ_EMAIL on PRACTICE_SPEAKER (EMAIL)^
create index LAST_NAME_INDEX on PRACTICE_SPEAKER (LAST_NAME)^
-- end PRACTICE_SPEAKER
