alter table CUBAPROJECT1_SESSION add constraint FK_CUBAPROJECT1_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references CUBAPROJECT1_SPEAKER(ID);
create index IDX_CUBAPROJECT1_SESSION_ON_SPEAKER on CUBAPROJECT1_SESSION (SPEAKER_ID);
