-- begin CUBATRY_SESSION
alter table CUBATRY_SESSION add constraint FK_CUBATRY_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references CUBATRY_SPEAKER(ID)^
create index IDX_CUBATRY_SESSION_ON_SPEAKER on CUBATRY_SESSION (SPEAKER_ID)^
-- end CUBATRY_SESSION
-- begin CUBATRY_SPEAKER
create unique index IDX_CUBATRY_SPEAKER_UNIQ_EMAIL on CUBATRY_SPEAKER (EMAIL)^
create index LAST_NAME_INDEX on CUBATRY_SPEAKER (LAST_NAME)^
-- end CUBATRY_SPEAKER
