alter table PRACTICE_SESSION add constraint FK_PRACTICE_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references PRACTICE_SPEAKER(ID);
create index IDX_PRACTICE_SESSION_ON_SPEAKER on PRACTICE_SESSION (SPEAKER_ID);
