alter table CUBATRY_SESSION add constraint FK_CUBATRY_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references CUBATRY_SPEAKER(ID);
create index IDX_CUBATRY_SESSION_ON_SPEAKER on CUBATRY_SESSION (SPEAKER_ID);
