-- begin HOSPITAL_PEOPLE
alter table HOSPITAL_PEOPLE add constraint FK_HOSPITAL_PEOPLE_ON_WARDS foreign key (WARDS_ID) references HOSPITAL_WARDS(ID)^
alter table HOSPITAL_PEOPLE add constraint FK_HOSPITAL_PEOPLE_ON_DIAGNOSIS foreign key (DIAGNOSIS_ID) references HOSPITAL_DIAGNOSIS(ID)^
create index IDX_HOSPITAL_PEOPLE_ON_WARDS on HOSPITAL_PEOPLE (WARDS_ID)^
create index IDX_HOSPITAL_PEOPLE_ON_DIAGNOSIS on HOSPITAL_PEOPLE (DIAGNOSIS_ID)^
-- end HOSPITAL_PEOPLE
