alter table HOSPITAL_PEOPLE add constraint FK_HOSPITAL_PEOPLE_ON_DIAGNOSIS foreign key (DIAGNOSIS_ID) references HOSPITAL_DIAGNOSIS(ID);
create index IDX_HOSPITAL_PEOPLE_ON_DIAGNOSIS on HOSPITAL_PEOPLE (DIAGNOSIS_ID);
